# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gravatar-ultimate}
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Colin MacKenzie IV"]
  s.date = %q{2010-08-30}
  s.description = %q{The Ultimate Gravatar Gem!

This gem is used to interface with the entire Gravatar API: it's not just for generating image URLs, but for connecting
to and communicating with the XML-RPC API too! Additionally, it can be used to download the Gravatar image data itself,
rather than just a URL to that data. This saves you the extra step of having to do so.}
  s.email = %q{sinisterchipmunk@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "gravatar-ultimate.gemspec",
     "lib/gravatar-ultimate.rb",
     "lib/gravatar.rb",
     "lib/gravatar/cache.rb",
     "lib/gravatar/dependencies.rb",
     "lib/gravatar_ultimate.rb",
     "spec/credentials.yml.example",
     "spec/fixtures/image.jpg",
     "spec/lib/gravatar/cache_and_logger_spec.rb",
     "spec/lib/gravatar/cache_setup_spec.rb",
     "spec/lib/gravatar/dependencies_spec.rb",
     "spec/lib/gravatar_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://www.thoughtsincomputation.com/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A gem for interfacing with the entire Gravatar API: not just images, but the XML-RPC API too!}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/lib/gravatar_spec.rb",
     "spec/lib/gravatar/dependencies_spec.rb",
     "spec/lib/gravatar/cache_and_logger_spec.rb",
     "spec/lib/gravatar/cache_setup_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sc-core-ext>, [">= 1.2.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.8"])
    else
      s.add_dependency(%q<sc-core-ext>, [">= 1.2.0"])
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
    end
  else
    s.add_dependency(%q<sc-core-ext>, [">= 1.2.0"])
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
  end
end

